version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: travel_mongo
    ports:
      - "27020:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  mongo-express:
    image: mongo-express
    container_name: travel_mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo

  redis:
    image: redis:7
    container_name: travel_redis
    ports:
      - "6380:6379"
    restart: always

  neo4j:
    image: neo4j:5
    container_name: travel_neo4j
    ports:
      - "7474:7474" # Neo4j Browser
      - "7777:7687" # Bolt protocol
    environment:
      - NEO4J_AUTH=none # Authentification désactivée
    volumes:
      - neo4j_data:/data
    restart: always

  api:
    build:
      context: .
      dockerfile: TravelPlanner.Api/Dockerfile
    container_name: travel_api
    ports:
      - "5059:5059"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongo
      - redis
      - neo4j

volumes:
  mongo_data:
  neo4j_data:
